# Titanic Survival Prediction using NAIVE BAYES

# 1. Importing libraries

In [1]:
import pandas as pd
import numpy as np

# 2. load the dataset

In [2]:
dataset = pd.read_csv('titanicsurvival.csv')

In [3]:
dataset

     Pclass  Gender   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

# 3. Summarize dataset

In [4]:
dataset.shape

(891, 5)

In [5]:
dataset.isnull().sum()

Pclass        0
Gender        0
Age         177
Fare          0
Survived      0
dtype: int64

In [6]:
dataset.head(5)

   Pclass  Gender   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

# 4. Mapping Text data to binary Value

In [7]:
income_set = set(dataset['Gender'])
dataset['Gender'] = dataset['Gender'].map({'female':0,'male':1}).astype(int)
print(dataset.head())

   Pclass  Gender   Age     Fare  Survived
0       3       1  22.0   7.2500         0
1       1       0  38.0  71.2833         1
2       3       0  26.0   7.9250         1
3       1       0  35.0  53.1000         1
4       3       1  35.0   8.0500         0

In [8]:
dataset.dtypes

Pclass        int64
Gender        int64
Age         float64
Fare        float64
Survived      int64
dtype: object

# 5. Segregate Dataset into X(input) and Y(output)

In [9]:
X = dataset.drop('Survived',axis='columns')
X

     Pclass  Gender   Age     Fare
0         3       1  22.0   7.2500
1         1       0  38.0  71.2833
2         3       0  26.0   7.9250
3         1       0  35.0  53.1000
4         3       1  35.0   8.0500
..      ...     ...   ...      ...
886       2       1  27.0  13.0000
887       1       0  19.0  30.0000
888       3       0   NaN  23.4500
889       1       1  26.0  30.0000
890       3       1  32.0   7.7500

[891 rows x 4 columns]

In [11]:
Y = dataset['Survived']
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

# 6. Finding and removing NA values from our Features X

In [17]:
X.columns[X.isna().any()]

Index([], dtype='object')

In [18]:
X.Age = X.Age.fillna(X.Age.mean())

In [19]:
dataset

     Pclass  Gender   Age     Fare  Survived
0         3       1  22.0   7.2500         0
1         1       0  38.0  71.2833         1
2         3       0  26.0   7.9250         1
3         1       0  35.0  53.1000         1
4         3       1  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2       1  27.0  13.0000         0
887       1       0  19.0  30.0000         1
888       3       0   NaN  23.4500         0
889       1       1  26.0  30.0000         1
890       3       1  32.0   7.7500         0

[891 rows x 5 columns]

# 7. Test again to check any na value

In [20]:
X.columns[X.isna().any()]

Index([], dtype='object')

# 8. Splitting Dataset into Train and Test

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

# 9. Training

In [23]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

# 10. Prediction for all test Data

In [26]:
y_pred = model.predict(X_test)
print(np.column_stack((y_pred,y_test)))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]

# 11. Accuracy of the Model

In [27]:
from sklearn.metrics import accuracy_score
print("Accuracy of the Model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the Model: 77.57847533632287%

# 12. Predicting,wheather person Survived or not

In [30]:
pclassNo = int(input("Enter Person's Pclass number: "))
gender = int(input("Enter Person's Gender 0-female/ 1-male: "))
age = int(input("Enter Person's Age: "))
fare = float(input("Enter Person's Fare: "))
person = [[pclassNo,gender,age,fare]]
res = model.predict(person)
print(res)

if res == 1:
    print("Person might be Survived!")
else:
    print("Person might not be Survived!")

Enter Person's Pclass number:  1
Enter Person's Gender 0-female/ 1-male:  0
Enter Person's Age:  58
Enter Person's Fare:  58.6

[1]
Person might be Survived!

C:\Users\MOHANASUNDARAM.M\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

#  THE END!!!