## Chapter 1: Getting and knowing your data
- step 1: give a suitable name for the dataset

In [1]:
import pandas as pd

In [10]:
order_details = pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep = "\t")

In [9]:
pd.read_csv(filepath_or_buffer = "medical_data_100.csv",sep=",")

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,P001,Neha,40,Female,O-,Migraine,Dr. Reddy,2025-02-06
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
2,P003,Meena,31,Female,B+,Fever,Dr. Sharma,2025-07-08
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
...,...,...,...,...,...,...,...,...
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
96,P097,Kumar,20,Male,AB-,Diabetes,Dr. Mehta,2025-04-09
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06
98,P099,Ravi,32,Female,O-,Asthma,Dr. Reddy,2025-08-08
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

##### insights(client data) -or- meaning insights (me identified and tell to client)

In [11]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1Perform initail Analysis
- shape
- null entrires check
- describe
- dtype check

In [13]:
# function -> always end with open and close bracket
# Attribute -> it does not return any value
order_details.shape

(4622, 5)

#### Terminalogy alert
- rows - observation/Record
- columns - features/Parameters

In [17]:
order_details.isnull().sum() # find the null values , #chain of functions

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [18]:
# very important function describitive values
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [19]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [20]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

## 1.2 Find out the items sold in the restaurent

In [21]:
order_details.nunique() # find the unique data

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [22]:
order_details["item_name"]

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

In [24]:
order_details["item_name"].unique() # finding all the items name in the dataset

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

## 1.3 Give me the list of Top 5 selling item

In [27]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values()

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [30]:
order_details.sort_values(by="quantity",ascending=False)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
4152,1660,10,Bottled Water,NaN,$15.00
3887,1559,8,Side of Chips,NaN,$13.52
3599,1443,7,Bottled Water,NaN,$10.50
2441,970,5,Bottled Water,NaN,$7.50
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49

In [31]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [33]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head(10)

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## Give me the list of least 5 selling items

In [37]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64