In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("medical_data_100.csv")

In [9]:
df

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,P001,Neha,40,Female,O-,Migraine,Dr. Reddy,2025-02-06
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
2,P003,Meena,31,Female,B+,Fever,Dr. Sharma,2025-07-08
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
...,...,...,...,...,...,...,...,...
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
96,P097,Kumar,20,Male,AB-,Diabetes,Dr. Mehta,2025-04-09
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06
98,P099,Ravi,32,Female,O-,Asthma,Dr. Reddy,2025-08-08
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [4]:
df.head()

  Patient_ID   Name  Age  Gender Blood_Group Diagnosis      Doctor  Visit_Date
0       P001   Neha   40  Female          O-  Migraine   Dr. Reddy  2025-02-06
1       P002  Meena   68  Female          O+    Asthma   Dr. Reddy  2025-05-10
2       P003  Meena   31  Female          B+     Fever  Dr. Sharma  2025-07-08
3       P004  Divya   60  Female          O+     Fever  Dr. Sharma  2025-10-31
4       P005  Priya   67    Male          B+    Asthma   Dr. Mehta  2025-10-22

In [5]:
df.tail()

   Patient_ID   Name  Age  Gender Blood_Group Diagnosis     Doctor  Visit_Date
95       P096  Anita   75    Male          A-       Flu  Dr. Reddy  2025-08-18
96       P097  Kumar   20    Male         AB-  Diabetes  Dr. Mehta  2025-04-09
97       P098  Priya   19  Female          A+     Fever  Dr. Kumar  2025-04-06
98       P099   Ravi   32  Female          O-    Asthma  Dr. Reddy  2025-08-08
99       P100   Ravi   69    Male          A-       Flu  Dr. Reddy  2025-09-04

In [6]:
df.columns

Index(['Patient_ID', 'Name', 'Age', 'Gender', 'Blood_Group', 'Diagnosis',
       'Doctor', 'Visit_Date'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Patient_ID   100 non-null    object
 1   Name         100 non-null    object
 2   Age          100 non-null    int64
 3   Gender       100 non-null    object
 4   Blood_Group  100 non-null    object
 5   Diagnosis    100 non-null    object
 6   Doctor       100 non-null    object
 7   Visit_Date   100 non-null    object
dtypes: int64(1), object(7)
memory usage: 6.4+ KB

In [8]:
df["Age"]

0     40
1     68
2     31
3     60
4     67
      ..
95    75
96    20
97    19
98    32
99    69
Name: Age, Length: 100, dtype: int64

In [9]:
df["Blood_Group"]

0      O-
1      O+
2      B+
3      O+
4      B+
     ...
95     A-
96    AB-
97     A+
98     O-
99     A-
Name: Blood_Group, Length: 100, dtype: object

In [10]:
df["Blood_Group"].head()

0    O-
1    O+
2    B+
3    O+
4    B+
Name: Blood_Group, dtype: object

In [11]:
df[["Name","Age"]].tail()

     Name  Age
95  Anita   75
96  Kumar   20
97  Priya   19
98   Ravi   32
99   Ravi   69

In [12]:
df.loc[0]

Patient_ID           P001
Name                 Neha
Age                    40
Gender             Female
Blood_Group            O-
Diagnosis        Migraine
Doctor          Dr. Reddy
Visit_Date     2025-02-06
Name: 0, dtype: object

In [13]:
df.loc[50]

Patient_ID             P051
Name                  Priya
Age                      39
Gender               Female
Blood_Group             AB+
Diagnosis      Hypertension
Doctor           Dr. Sharma
Visit_Date       2025-04-23
Name: 50, dtype: object

In [14]:
df[df["Age"] > 40]

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
5,P006,Ravi,53,Male,A+,Flu,Dr. Mehta,2025-08-14
6,P007,Priya,80,Female,A-,Fever,Dr. Mehta,2025-07-31
...,...,...,...,...,...,...,...,...
86,P087,Suresh,47,Male,A+,Migraine,Dr. Sharma,2025-04-13
92,P093,Kumar,75,Female,A-,Asthma,Dr. Mehta,2025-05-25
93,P094,Anita,47,Male,B-,Hypertension,Dr. Reddy,2025-05-24
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [5]:
df[df["Diagnosis"] == "Fever"]

NameError: name 'df' is not defined

In [16]:
df[df["Diagnosis"] == "Flu"]

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
5,P006,Ravi,53,Male,A+,Flu,Dr. Mehta,2025-08-14
21,P022,Kumar,66,Male,O-,Flu,Dr. Mehta,2025-03-06
22,P023,Vikram,64,Male,O-,Flu,Dr. Kumar,2025-06-22
24,P025,Suresh,71,Female,O+,Flu,Dr. Mehta,2025-06-02
45,P046,Priya,43,Female,A+,Flu,Dr. Sharma,2025-01-23
53,P054,Suresh,43,Male,O-,Flu,Dr. Mehta,2025-06-18
60,P061,Neha,50,Male,AB-,Flu,Dr. Kumar,2025-04-11
63,P064,Divya,35,Female,A+,Flu,Dr. Sharma,2025-12-08
79,P080,Arun,33,Female,O+,Flu,Dr. Mehta,2025-06-18
84,P085,Suresh,54,Male,B-,Flu,Dr. Reddy,2025-10-14
87,P088,Kumar,36,Male,AB-,Flu,Dr. Mehta,2026-01-01
94,P095,Meena,33,Male,AB+,Flu,Dr. Reddy,2025-07-02
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [17]:
df[df["Gender"] == "Male"]

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
5,P006,Ravi,53,Male,A+,Flu,Dr. Mehta,2025-08-14
8,P009,Kumar,47,Male,B+,Hypertension,Dr. Mehta,2025-11-17
9,P010,Anita,73,Male,A-,Asthma,Dr. Mehta,2025-07-09
10,P011,Suresh,70,Male,O+,Diabetes,Dr. Sharma,2025-02-12
12,P013,Neha,30,Male,AB+,Migraine,Dr. Sharma,2025-07-05
14,P015,Meena,73,Male,A+,Diabetes,Dr. Reddy,2025-02-12
15,P016,Priya,22,Male,B+,Hypertension,Dr. Kumar,2025-04-16
17,P018,Anita,56,Male,B+,Hypertension,Dr. Kumar,2025-08-18
18,P019,Divya,56,Male,B+,Migraine,Dr. Sharma,2025-12-27
19,P020,Vikram,29,Male,O+,Asthma,Dr. Sharma,2025-10-31
20,P021,Suresh,51,Male,A-,Fever,Dr. Mehta,2025-12-26
21,P022,Kumar,66,Male,O-,Flu,Dr. Mehta,2025-03-06
22,P023,Vikram,64,Male,O-,Flu,Dr. Kumar,2025-06-22
29,P030,Vikram,28,Male,O+,Hypertension,Dr. Sharma,2025-12-01
30,P031,Neha,60,Male,O+,Asthma,Dr. Mehta,2025-03-01
31,P032,Ravi,50,Male,B+,Diabetes,Dr. Reddy,2025-02-18
32,P033,Ravi,26,Male,AB-,Asthma,Dr. Kumar,2025-03-20
34,P035,Kumar,31,Male,B+,Diabetes,Dr. Kumar,2025-11-20
39,P040,Meena,26,Male,O+,Fever,Dr. Sharma,2025-05-08
43,P044,Priya,34,Male,AB+,Fever,Dr. Sharma,2025-05-17
48,P049,Divya,19,Male,A-,Asthma,Dr. Mehta,2025-04-06
53,P054,Suresh,43,Male,O-,Flu,Dr. Mehta,2025-06-18
54,P055,Kumar,41,Male,O-,Hypertension,Dr. Mehta,2025-12-16
55,P056,Vikram,36,Male,B+,Asthma,Dr. Reddy,2025-04-30
57,P058,Ravi,41,Male,AB+,Migraine,Dr. Reddy,2025-09-06
59,P060,Anita,36,Male,AB+,Migraine,Dr. Mehta,2025-06-05
60,P061,Neha,50,Male,AB-,Flu,Dr. Kumar,2025-04-11
61,P062,Anita,32,Male,B+,Fever,Dr. Sharma,2025-11-02
66,P067,Ravi,35,Male,AB-,Asthma,Dr. Kumar,2025-07-09
67,P068,Arun,46,Male,O+,Diabetes,Dr. Sharma,2025-03-13
69,P070,Anita,79,Male,B+,Asthma,Dr. Mehta,2025-09-17
70,P071,Divya,67,Male,AB-,Fever,Dr. Sharma,2025-05-22
72,P073,Priya,58,Male,B-,Diabetes,Dr. Kumar,2025-06-01
76,P077,Kumar,61,Male,B-,Diabetes,Dr. Sharma,2025-06-30
78,P079,Kumar,59,Male,AB-,Diabetes,Dr. Kumar,2025-12-14
80,P081,Ravi,27,Male,O-,Fever,Dr. Kumar,2025-12-11
84,P085,Suresh,54,Male,B-,Flu,Dr. Reddy,2025-10-14
85,P086,Suresh,66,Male,AB-,Fever,Dr. Sharma,2025-06-09
86,P087,Suresh,47,Male,A+,Migraine,Dr. Sharma,2025-04-13
87,P088,Kumar,36,Male,AB-,Flu,Dr. Mehta,2026-01-01
89,P090,Kumar,20,Male,A-,Asthma,Dr. Mehta,2025-09-25
93,P094,Anita,47,Male,B-,Hypertension,Dr. Reddy,2025-05-24
94,P095,Meena,33,Male,AB+,Flu,Dr. Reddy,2025-07-02
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
96,P097,Kumar,20,Male,AB-,Diabetes,Dr. Mehta,2025-04-09
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [10]:
df[(df["Age"] > 40) & (df["Gender"] == "Male")]

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
5,P006,Ravi,53,Male,A+,Flu,Dr. Mehta,2025-08-14
8,P009,Kumar,47,Male,B+,Hypertension,Dr. Mehta,2025-11-17
9,P010,Anita,73,Male,A-,Asthma,Dr. Mehta,2025-07-09
10,P011,Suresh,70,Male,O+,Diabetes,Dr. Sharma,2025-02-12
14,P015,Meena,73,Male,A+,Diabetes,Dr. Reddy,2025-02-12
17,P018,Anita,56,Male,B+,Hypertension,Dr. Kumar,2025-08-18
18,P019,Divya,56,Male,B+,Migraine,Dr. Sharma,2025-12-27
20,P021,Suresh,51,Male,A-,Fever,Dr. Mehta,2025-12-26
21,P022,Kumar,66,Male,O-,Flu,Dr. Mehta,2025-03-06
22,P023,Vikram,64,Male,O-,Flu,Dr. Kumar,2025-06-22
30,P031,Neha,60,Male,O+,Asthma,Dr. Mehta,2025-03-01
31,P032,Ravi,50,Male,B+,Diabetes,Dr. Reddy,2025-02-18
53,P054,Suresh,43,Male,O-,Flu,Dr. Mehta,2025-06-18
54,P055,Kumar,41,Male,O-,Hypertension,Dr. Mehta,2025-12-16
57,P058,Ravi,41,Male,AB+,Migraine,Dr. Reddy,2025-09-06
60,P061,Neha,50,Male,AB-,Flu,Dr. Kumar,2025-04-11
67,P068,Arun,46,Male,O+,Diabetes,Dr. Sharma,2025-03-13
69,P070,Anita,79,Male,B+,Asthma,Dr. Mehta,2025-09-17
70,P071,Divya,67,Male,AB-,Fever,Dr. Sharma,2025-05-22
72,P073,Priya,58,Male,B-,Diabetes,Dr. Kumar,2025-06-01
76,P077,Kumar,61,Male,B-,Diabetes,Dr. Sharma,2025-06-30
78,P079,Kumar,59,Male,AB-,Diabetes,Dr. Kumar,2025-12-14
84,P085,Suresh,54,Male,B-,Flu,Dr. Reddy,2025-10-14
85,P086,Suresh,66,Male,AB-,Fever,Dr. Sharma,2025-06-09
86,P087,Suresh,47,Male,A+,Migraine,Dr. Sharma,2025-04-13
93,P094,Anita,47,Male,B-,Hypertension,Dr. Reddy,2025-05-24
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [11]:
df.isnull().sum()

Patient_ID     0
Name           0
Age            0
Gender         0
Blood_Group    0
Diagnosis      0
Doctor         0
Visit_Date     0
dtype: int64

In [12]:
df.isnull()

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Patient_ID     0
Name           0
Age            0
Gender         0
Blood_Group    0
Diagnosis      0
Doctor         0
Visit_Date     0
dtype: int64

In [14]:
df.fillna(0,inplace = True)

In [16]:

df.rename(columns={"Name":"Patient_Name"},inplace = True)

In [17]:
df

,Patient_ID,Patient_Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,P001,Neha,40,Female,O-,Migraine,Dr. Reddy,2025-02-06
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
2,P003,Meena,31,Female,B+,Fever,Dr. Sharma,2025-07-08
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
...,...,...,...,...,...,...,...,...
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
96,P097,Kumar,20,Male,AB-,Diabetes,Dr. Mehta,2025-04-09
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06
98,P099,Ravi,32,Female,O-,Asthma,Dr. Reddy,2025-08-08
99,P100,Ravi,69,Male,A-,Flu,Dr. Reddy,2025-09-04

In [18]:
df.head()

,Patient_ID,Patient_Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,P001,Neha,40,Female,O-,Migraine,Dr. Reddy,2025-02-06
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
2,P003,Meena,31,Female,B+,Fever,Dr. Sharma,2025-07-08
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22

In [19]:
df["Age"].mean()

np.float64(48.11)

In [20]:
df["Gender"].mean()

TypeError: Could not convert string 'FemaleFemaleFemaleFemaleMaleMaleFemaleFemaleMaleMaleMaleFemaleMaleFemaleMaleMaleFemaleMaleMaleMaleMaleMaleMaleFemaleFemaleFemaleFemaleFemaleFemaleMaleMaleMaleMaleFemaleMaleFemaleFemaleFemaleFemaleMaleFemaleFemaleFemaleMaleFemaleFemaleFemaleFemaleMaleFemaleFemaleFemaleFemaleMaleMaleMaleFemaleMaleFemaleMaleMaleMaleFemaleFemaleFemaleFemaleMaleMaleFemaleMaleMaleFemaleMaleFemaleFemaleFemaleMaleFemaleMaleFemaleMaleFemaleFemaleFemaleMaleMaleMaleMaleFemaleMaleFemaleFemaleFemaleMaleMaleMaleMaleFemaleFemaleMale' to numeric

In [21]:
df["Age"].sum()

np.int64(4811)

In [22]:
df["Age"].max()

np.int64(80)

In [23]:
df["Age"].min()

np.int64(19)

In [24]:
df.describe()

              Age
count  100.000000
mean    48.110000
std     17.623386
min     19.000000
25%     32.000000
50%     48.000000
75%     64.000000
max     80.000000

In [25]:
df.groupby("Diagnosis")["Age"].mean()

Diagnosis
Asthma          47.777778
Diabetes        54.625000
Fever           43.100000
Flu             51.785714
Hypertension    46.000000
Migraine        47.000000
Name: Age, dtype: float64

In [26]:
df.groupby("Visit_Date")["Age"].mean()

Visit_Date
2025-01-02    20.0
2025-01-03    49.0
2025-01-15    64.0
2025-01-16    70.0
2025-01-23    43.0
              ...
2025-12-14    59.0
2025-12-16    41.0
2025-12-26    51.0
2025-12-27    56.0
2026-01-01    36.0
Name: Age, Length: 91, dtype: float64

In [28]:
df.groupby("Diagnosis")["Blood_Group"]

In [29]:
df.sort_values("Age",ascending=False)

,Patient_ID,Patient_Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
6,P007,Priya,80,Female,A-,Fever,Dr. Mehta,2025-07-31
69,P070,Anita,79,Male,B+,Asthma,Dr. Mehta,2025-09-17
33,P034,Meena,77,Female,B-,Asthma,Dr. Sharma,2025-02-16
27,P028,Meena,77,Female,AB+,Fever,Dr. Reddy,2025-10-03
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
...,...,...,...,...,...,...,...,...
89,P090,Kumar,20,Male,A-,Asthma,Dr. Mehta,2025-09-25
90,P091,Anita,20,Female,AB+,Migraine,Dr. Sharma,2025-01-02
48,P049,Divya,19,Male,A-,Asthma,Dr. Mehta,2025-04-06
88,P089,Suresh,19,Female,A-,Asthma,Dr. Sharma,2025-09-27
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06

In [30]:
df.sort("Age")

AttributeError: 'DataFrame' object has no attribute 'sort'

In [31]:
df.sort("Age", ascending=True)

AttributeError: 'DataFrame' object has no attribute 'sort'

In [32]:
df.sort_values("Age")

,Patient_ID,Patient_Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
48,P049,Divya,19,Male,A-,Asthma,Dr. Mehta,2025-04-06
88,P089,Suresh,19,Female,A-,Asthma,Dr. Sharma,2025-09-27
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06
82,P083,Priya,20,Female,AB+,Hypertension,Dr. Kumar,2025-05-16
90,P091,Anita,20,Female,AB+,Migraine,Dr. Sharma,2025-01-02
...,...,...,...,...,...,...,...,...
92,P093,Kumar,75,Female,A-,Asthma,Dr. Mehta,2025-05-25
27,P028,Meena,77,Female,AB+,Fever,Dr. Reddy,2025-10-03
33,P034,Meena,77,Female,B-,Asthma,Dr. Sharma,2025-02-16
69,P070,Anita,79,Male,B+,Asthma,Dr. Mehta,2025-09-17
6,P007,Priya,80,Female,A-,Fever,Dr. Mehta,2025-07-31

In [34]:
df["Age"].value_counts()

Age
47    5
56    5
31    4
36    4
20    4
26    4
52    3
66    3
64    3
35    3
19    3
70    3
32    3
69    3
41    3
28    2
77    2
33    2
75    2
43    2
67    2
73    2
30    2
60    2
68    2
53    2
50    2
61    2
74    2
29    2
40    1
22    1
37    1
49    1
80    1
34    1
55    1
51    1
71    1
46    1
57    1
39    1
79    1
59    1
58    1
27    1
54    1
Name: count, dtype: int64

In [35]:
df["Blood_Group"].value_counts()

Blood_Group
O+     18
A-     15
B+     14
AB+    13
A+     11
O-     10
AB-    10
B-      9
Name: count, dtype: int64