### 1.write a program to take a name and age from the user and print a greeting message

In [1]:
user_name = input("Enter Name: ")
user_age = input("Enter Age:")
print(f"Hello {user_name}, Welcome to coding part, Please confirm age: {user_age}")

Enter Name:  kumar
Enter Age: 20

Hello kumar, Welcome to coding part, Please confirm age: 20

### 2. Create a list of numbers and print only even numbers using a loop

In [4]:
numbers = range(1,20)
even_numbers = []
for i in numbers:
    if i%2 == 0:
        even_numbers.append(i)
even_numbers

[2, 4, 6, 8, 10, 12, 14, 16, 18]

### 3. Write a program that handles division by zero using try-except

In [12]:
try:
    numerator = int(input("Enter numerator: "))
    denominator = int(input("Enter denominator: "))
    res = numerator/denominator
    print(res)
except ZeroDivisionError:
    print("Invalid Entry! Enter a number orther than zero!")
except ValueError:
    print("Invalud Entry! Enter a number not alphabets!")
finally:
    print("Program Ended!")

Enter numerator:  100
Enter denominator:  10

10.0
Program Ended!

### 4.Given a String, count how many vowels it has.

In [16]:
user_input = input("Enter any word or sentence: ")
cnt = 0
for i in user_input.lower():
    if i in 'aeiou':
        cnt = cnt+1
cnt

Enter any word or sentence:  Dhinesh KUmar

4

### 5.Reverse a list without using built-in functions

In [26]:
original_list = [1,2,3,4,5]
new_list = []
l=0
r = len(original_list)-1
while l<=r:
    temp = original_list[l]
    original_list[l] = original_list[r]
    original_list[r] = temp;
    l = l+1;
    r = r-1;
original_list

[5, 4, 3, 2, 1]

### 6. Create a dictionary with at least 5 key-value pairs and print them

In [27]:
import pandas as pd

In [29]:
pd.DataFrame(data ={"First Name":["kumar","raj","dharshini"],
                  "Last Name":["dhinesh","striver","dhinesh kumar"]})

  First Name      Last Name
0      kumar        dhinesh
1        raj        striver
2  dharshini  dhinesh kumar

### Replace all missing values in a DataFrame with the column's mean

In [1]:
import pandas as pd

In [12]:
emp_data = pd.read_csv("employee_data.csv")

In [13]:
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [10]:
emp_data["Salary"].mean()

KeyError: 'Salary'

In [7]:
emp_data = emp_data["Salary"].fillna(value = emp_data["Salary"].mean())

In [8]:
emp_data

0    60000.0
1    62500.0
2    58000.0
3    60000.0
4    61000.0
5    72000.0
6    64000.0
7    62500.0
Name: Salary, dtype: float64

In [16]:
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

In [17]:
emp_data["Salary"].fillna(value = emp_data["Salary"].mean(),inplace = True)

C:\Users\MOHANASUNDARAM.M\AppData\Local\Temp\ipykernel_9976\2930723595.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  emp_data["Salary"].fillna(value = emp_data["Salary"].mean(),inplace = True)

In [18]:
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### Filter rows in a DataFrame where the "Age" column is greater than 30

In [19]:
emp_data[emp_data["Age"] > 30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020

### Write a pandas code to read a CSV and print the top 5 rows

In [20]:
import pandas as pd

In [21]:
emp_details = pd.read_csv("employee_data.csv")

In [22]:
emp_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [23]:
emp_details.head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024