In [ ]:
--- CEO roles
-trainer
-content writer
-video editing
-sales
-graphics designer

In [2]:
#Data structures
#lists,tuples,dictonaries,sets

## Why python data structures
-To collect multiple data in a structure

### LIST
- list accepts duplicates values
- list is mutable
- slicing can be done
- list is hetergoneous data types
- indexing ans slicing is possible

In [3]:
student_mark = 67,78,10,100,90

In [4]:
student_mark

(67, 78, 10, 100, 90)

In [6]:
type (student_mark)

tuple

In [7]:
empty_cart = []

In [8]:
empty_cart

[]

In [9]:
type(empty_cart)

list

In [12]:
items_to_buy = ["Apple","Orange","Graphes","Gauva","Apple"]
items_to_buy

['Apple', 'Orange', 'Graphes', 'Gauva', 'Apple']

In [13]:
items_to_buy = ["Apple","Orange","Graphes","Gauva","Apple",6.75,10]
items_to_buy

['Apple', 'Orange', 'Graphes', 'Gauva', 'Apple', 6.75, 10]

In [ ]:
# slicing is done by index start from 0, using the len function return the number of items in a contains

In [14]:
len(items_to_buy)

7

In [15]:
items_to_buy[0] # indexing

'Apple'

In [18]:
items_to_buy[0:2] # start = 0, end = len+1 always use -> data is start to end index -1 , this concept called as range of valuse

['Apple', 'Orange']

In [21]:
items_to_buy[-3] # negative indexing is also positive -> traverse from right to left

'Apple'

In [22]:
items_to_buy[2:6]

['Graphes', 'Gauva', 'Apple', 6.75]

In [25]:
items_to_buy[-7:-4] # end : start

['Apple', 'Orange', 'Graphes']

In [28]:
#changing the values in future
items_to_buy[1] = "Watermelon" # this process is called mutable

In [27]:
items_to_buy

['Apple', 'Watermelon', 'Graphes', 'Gauva', 'Apple', 6.75, 10]

## Sets
- set does not allow duplicates
- 1D
- it is hetergenous
- indexing and Slicing is not possible
- set is mutable

In [29]:
secret_values = 723,234,234.234

In [30]:
secret_values

(723, 234, 234.234)

In [33]:
empty_cart2 = set()

In [34]:
empty_cart2

set()

In [35]:
type(empty_cart2)

set

In [2]:
items_to_buy2 = {"Apple","Orange","Graphes","Gauva","Apple",23}
items_to_buy2 # set does not allow duplicates && it is one-dimensional && it is hetergenous

{23, 'Apple', 'Gauva', 'Graphes', 'Orange'}

In [3]:
items_to_buy2[2] # 'set' object is not subscriptable -> means that indexing and Slicing is not possible

TypeError: 'set' object is not subscriptable

In [4]:
# how set is mutable?
# adding an element
items_to_buy2.add("banana")

#removing an element
items_to_buy2.discard("Graphes")

In [5]:
items_to_buy2

{23, 'Apple', 'Gauva', 'Orange', 'banana'}

In [7]:
items_to_buy2.append("Red banana")

AttributeError: 'set' object has no attribute 'append'

## 3. Tuple
- tuple is immutable
- 1D
- hetergenous ds
- duplicates allowed
- indexing and slicing is allowed

In [8]:
data = ("spam","apps")
data

('spam', 'apps')

In [9]:
type(data)

tuple

In [10]:
empty_cart_tuple = ()

In [11]:
empty_cart_tuple

()

In [12]:
items = ("Apple","Banana","Cherry","Apple")

In [13]:
items

('Apple', 'Banana', 'Cherry', 'Apple')

In [14]:
items[0]

'Apple'

In [15]:
items[0:3]

('Apple', 'Banana', 'Cherry')

In [16]:
items[3] = "Red banana"

TypeError: 'tuple' object does not support item assignment

In [17]:
items.count(items)

0

In [18]:
count = items.value_counts()
count

AttributeError: 'tuple' object has no attribute 'value_counts'

In [20]:
items.count("Apple") # count is used to find how many number of time is repeated.

2

## 4. Dictionary
- it is a key value pair
- 2D
- Hetergenous
- Mutable
- indexing and slicing is not possible
- dont create duplicate key,but you can create duplicates values

In [21]:
empty_cart_dict = {}

In [22]:
empty_cart_dict

{}

In [23]:
type(empty_cart_dict)

dict

In [24]:
dict_data = {"Maths":95,"English":87,"Science":100}

In [25]:
dict_data

{'Maths': 95, 'English': 87, 'Science': 100}

In [26]:
type(dict_data)

dict

In [35]:
item_to_buy = {"Potato":5,"Tomata":10,"Apple":8}

In [36]:
item_to_buy

{'Potato': 5, 'Tomata': 10, 'Apple': 8}

In [31]:
item_to_buy[1]

KeyError: 1

In [32]:
#item_to_buy.clear()

In [37]:
item_to_buy.keys()

dict_keys(['Potato', 'Tomata', 'Apple'])

In [38]:
item_to_buy.values()

dict_values([5, 10, 8])

In [39]:
import pandas as pd

In [41]:
df = pd.DataFrame(item_to_buy) # it accepts 2D.

ValueError: If using all scalar values, you must pass an index

In [42]:
df

NameError: name 'df' is not defined

In [69]:
math_student_marks = {"Names":["Vijay","Ajay","kumar","sri","mirudula"],"Math":[67,78,32,65,56],"Science":[54,65,87,87,98],"Social":[100,90,34,65,34]}

In [70]:
math_student_marks

{'Names': ['Vijay', 'Ajay', 'kumar', 'sri', 'mirudula'],
 'Math': [67, 78, 32, 65, 56],
 'Science': [54, 65, 87, 87, 98],
 'Social': [100, 90, 34, 65, 34]}

In [71]:
pd.DataFrame(math_student_marks)

      Names  Math  Science  Social
0     Vijay    67       54     100
1      Ajay    78       65      90
2     kumar    32       87      34
3       sri    65       87      65
4  mirudula    56       98      34

In [68]:
df

   class 1  class 2
0       67       54
1       78       65
2       32       87
3       65       87

### THE END!!!

### How do you choose between List vs Set vs Tuple vs dictionary