# Logistics Regression : Classfication problem

# 1. import necessary libraries

In [2]:
import pandas as pd
from matplotlib import pyplot as plt

# 2.import data

In [19]:
gender_classfication = pd.read_csv('weight-height.csv')

In [20]:
gender_classfication

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

# 3. Data Understanding

In [21]:
gender_classfication.shape

(10000, 3)

In [22]:
gender_classfication.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [7]:
gender_classfication.dtypes

Gender     object
Height    float64
Weight    float64
dtype: object

# 4.Data Preparation

In [23]:
gender_classfication.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [24]:
gender_classfication['Gender'] = gender_classfication['Gender'].replace(to_replace=['Male','Female'],value=[0,1])

C:\Users\MOHANASUNDARAM.M\AppData\Local\Temp\ipykernel_14160\1702494385.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  gender_classfication['Gender'] = gender_classfication['Gender'].replace(to_replace=['Male','Female'],value=[0,1])

In [25]:
gender_classfication

      Gender     Height      Weight
0          0  73.847017  241.893563
1          0  68.781904  162.310473
2          0  74.110105  212.740856
3          0  71.730978  220.042470
4          0  69.881796  206.349801
...      ...        ...         ...
9995       1  66.172652  136.777454
9996       1  67.067155  170.867906
9997       1  63.867992  128.475319
9998       1  69.034243  163.852461
9999       1  61.944246  113.649103

[10000 rows x 3 columns]

In [26]:
gender_classfication.dtypes

Gender      int64
Height    float64
Weight    float64
dtype: object

In [27]:
gender_classfication['Height'] = gender_classfication['Height']*2.54
gender_classfication['Weight'] = gender_classfication['Weight']/2.205

# 5. Model Building

In [16]:
gender_classfication.drop(['Gender'],axis=1)

          Height      Weight
0     187.571423  109.702296
1     174.706036   73.610192
2     188.239668   96.481114
3     182.196685   99.792504
4     177.499761   93.582676
...          ...         ...
9995  168.078536   62.030591
9996  170.350573   77.491114
9997  162.224700   58.265451
9998  175.346978   74.309506
9999  157.338385   51.541543

[10000 rows x 2 columns]

In [17]:
gender_classfication

      Gender      Height      Weight
0          0  187.571423  109.702296
1          0  174.706036   73.610192
2          0  188.239668   96.481114
3          0  182.196685   99.792504
4          0  177.499761   93.582676
...      ...         ...         ...
9995       1  168.078536   62.030591
9996       1  170.350573   77.491114
9997       1  162.224700   58.265451
9998       1  175.346978   74.309506
9999       1  157.338385   51.541543

[10000 rows x 3 columns]

In [29]:
x = gender_classfication.drop(['Gender'],axis = 1)
y = gender_classfication[['Gender']]

# 6. Model Training

In [31]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(x,y)

C:\Users\MOHANASUNDARAM.M\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [32]:
logistic_model.coef_

array([[ 0.18835845, -0.43398554]])

In [33]:
logistic_model.intercept_

array([0.00348626])

# 7. Model Testing

In [35]:
y_pred = logistic_model.predict(x)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

0.9195

# 8. Model Deployment

In [39]:
from pickle import dump

In [40]:
dump(logistic_model,open('gender_classfication_intelligence.pkl','wb'))

#  THE END!